version: '3'

services:
  db:
    image: postgres:12.2
    env_file:
      - environment
      - .secrets
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: ./web
    volumes:
      - ./web/djangoproject:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - environment
      - .secrets
    command: python manage.py runserver 0.0.0.0:8000
volumes:
  db-data: