version: '3'

services:
  db:
    image: postgres:latest
    environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: ./web
    volumes:
      - ./web/djangoproject:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
volumes:
  db-data: